bpking1/embyExternalUrl

- emby2Alist/nginx/conf.d/emby.js
> Jellyfin 视频不同版本播放

- embyWebAddExternalUrl/embyLaunchPotplayer.js
感觉直接在当前页面拉起播放器比较方便？
而且iOS的Safari默认屏蔽弹窗，导致_blank的时候按钮直接失效😂
> window.open(url, '_self')

- emby2Alist/nginx/conf.d/common/util.js
- emby2Alist/nginx/conf.d/constant.js
- emby2Alist/nginx/conf.d/emby.js
如题，为 emby2Alist 添加了 sign 支持
但是我看到 [emby2Alist/README.md#L225](https://github.com/bpking1/embyExternalUrl/blob/50b926fbfbe1f6698013397ea37d02fa618a7bb4/emby2Alist/README.md?plain=1#L225) 提到说要兼容性能会很差，如果是我这样本地计算 sign 会导致性能低下吗？
> feat(emby2Alist): alist sign support

- embyWebAddExternalUrl/embyLaunchPotplayer.js
> fix(embyWebAddExternalUrl): 修复无当前集情况

- embyWebAddExternalUrl/embyLaunchPotplayer.js
> fix(embyWebAddExternalUrl): JellyfinWebMobileCss

- emby2Alist/nginx/conf.d/common/util.js
- emby2Alist/nginx/conf.d/emby.js
- plex2Alist/nginx/conf.d/common/util.js
- plex2Alist/nginx/conf.d/plex.js
https://github.com/chen3861229/embyExternalUrl/issues/52
> fix(emby2Alist&plex2Alist): 修复变量错误

- emby2Alist/nginx/conf.d/emby.js
- plex2Alist/nginx/conf.d/plex.js
https://github.com/chen3861229/embyExternalUrl/issues/52?notification_referrer_id=NT_kwDOAoZ_WLQxMTI5NDg3NDAxMTo0MjM2ODg1Ng
> fix(emby2Alist&plex2Alist): 修复被markdown误导的转义

- emby2Alist/nginx/conf.d/common/util.js
- plex2Alist/nginx/conf.d/common/util.js
https://github.com/bpking1/embyExternalUrl/issues/256
> fix(emby2Alist&plex2Alist): 修复getFilePathPart

- emby2Alist/nginx/conf.d/common/util.js
- plex2Alist/nginx/conf.d/common/util.js
https://github.com/bpking1/embyExternalUrl/issues/258
> fix(emby2Alist&plex2Alist): 区分mediaMountPath未定义或空数组

- embyWebAddExternalUrl/README.md
- embyWebAddExternalUrl/alistWebLaunchExternalPlayer.js
- embyWebAddExternalUrl/embyLaunchPotplayer.js
https://github.com/bpking1/embyExternalUrl/issues/275
> fix(embyWebAddExternalUrl): 修复mpv-handler编码错误

- FAQ.md
- emby2Alist/README.md
- emby2Alist/nginx/conf.d/common/util.js
- emby2Alist/nginx/conf.d/config/constant-nginx.js
- emby2Alist/nginx/conf.d/config/constant-strm.js
- emby2Alist/nginx/conf.d/constant.js
- emby2Alist/nginx/conf.d/emby.conf
- emby2Alist/nginx/conf.d/emby.js
- emby2Alist/nginx/conf.d/exampleConfig/constant-all.js
- emby2Alist/nginx/conf.d/modules/emby-search.js
- plex2Alist/README.md
- plex2Alist/nginx/conf.d/common/util.js
- plex2Alist/nginx/conf.d/config/constant-strm.js
- plex2Alist/nginx/conf.d/exampleConfig/constant-all.js
- plex2Alist/nginx/conf.d/plex.js
1.升级util.strMatches支持取反
2.禁用文档添加开关
3.修复变量未导出bug
https://github.com/bpking1/embyExternalUrl/issues/274
> feat(emby2Alist&plex2Alist): 禁用文档添加开关

- FAQ.md
- emby2Alist/nginx/conf.d/config/UA.txt
- emby2Alist/nginx/conf.d/config/constant-nginx.js
- emby2Alist/nginx/conf.d/config/constant-strm.js
- emby2Alist/nginx/conf.d/exampleConfig/constant-all.js
- plex2Alist/nginx/conf.d/config/constant-strm.js
- plex2Alist/nginx/conf.d/exampleConfig/constant-all.js
https://github.com/bpking1/embyExternalUrl/issues/289
> fix(emby2Alist): 修复导入错误

- emby2Alist/nginx/conf.d/config/constant-nginx.js
https://github.com/bpking1/embyExternalUrl/issues/289
https://github.com/bpking1/embyExternalUrl/issues/291
> fix(emby2Alist): 修复循环依赖

- emby2Alist/nginx/conf.d/common/util.js
- plex2Alist/nginx/conf.d/common/util.js
https://github.com/bpking1/embyExternalUrl/issues/291
> fix(emby2Alist&plex2Alist): 修复AlistSign

- emby2Alist/nginx/conf.d/common/util.js
- plex2Alist/nginx/conf.d/common/util.js
https://github.com/bpking1/embyExternalUrl/issues/256
> fix(emby2Alist&plex2Alist): 修复getFilePathPart正则

- FAQ.md
- emby2Alist/nginx/conf.d/common/util.js
- emby2Alist/nginx/conf.d/emby.conf
- emby2Alist/nginx/conf.d/modules/emby-search.js
- plex2Alist/nginx/conf.d/common/util.js
https://github.com/bpking1/embyExternalUrl/issues/321
> fix(emby2Alist&plex2Alist): 修复默认本地文件回源判断

- emby2Alist/README.md
- emby2Alist/nginx/conf.d/config/constant-common.js
- emby2Alist/nginx/conf.d/config/constant-pro.js
- emby2Alist/nginx/conf.d/emby.js
- emby2Alist/nginx/conf.d/exampleConfig/constant-all.js
- emby2Alist/nginx/conf.d/modules/emby-search.js
- plex2Alist/README.md
- plex2Alist/nginx/conf.d/config/constant-common.js
- plex2Alist/nginx/conf.d/config/constant-pro.js
- plex2Alist/nginx/conf.d/exampleConfig/constant-all.js
- plex2Alist/nginx/conf.d/plex.js
https://github.com/chen3861229/embyExternalUrl/issues/62
> feat(emby2Alist&plex2Alist): mediaPathMapping添加生效分组规则

- emby2Alist/nginx/conf.d/common/util.js
- emby2Alist/nginx/conf.d/constant.js
- emby2Alist/nginx/conf.d/emby.js
#322 
emby2Alist/nginx/conf.d/emby.js fetch115Transcode()
> feat(emby2Alist): 添加获取115转码直链、音源、字幕的函数

- emby2Alist/nginx/conf.d/config/constant-mount.js
- emby2Alist/nginx/conf.d/constant.js
- emby2Alist/nginx/conf.d/emby.js
- emby2Alist/nginx/conf.d/exampleConfig/constant-all.js
- emby2Alist/nginx/conf.d/exampleConfig/constant-main.js
- emby2Alist/nginx/conf.d/modules/emby-transcode.js
- emby2Alist/nginx/conf.d/modules/ngx-ext.js
- plex2Alist/nginx/conf.d/common/util.js
- plex2Alist/nginx/conf.d/config/constant-mount.js
- plex2Alist/nginx/conf.d/constant.js
- plex2Alist/nginx/conf.d/exampleConfig/constant-all.js
- plex2Alist/nginx/conf.d/exampleConfig/constant-main.js
- plex2Alist/nginx/conf.d/modules/ngx-ext.js
- plex2Alist/nginx/conf.d/plex.js
https://github.com/bpking1/embyExternalUrl/issues/347
https://github.com/bpking1/embyExternalUrl/issues/349
https://github.com/bpking1/embyExternalUrl/issues/348
> feat(emby2Alist&plex2Alist): 新增开关链接有效性检查

- emby2Alist/nginx/conf.d/common/url-util.js
- emby2Alist/nginx/conf.d/common/util.js
https://github.com/bpking1/embyExternalUrl/issues/344
> fix(emby2Alist): 修复新引入的bug老TV客户端

- emby2Alist/nginx/nginx.conf
- embyAddExternalUrl/nginx/nginx.conf
- plex2Alist/nginx/nginx.conf
https://github.com/chen3861229/embyExternalUrl/issues/69
> fix(emby2Alist&plex2Alist): 更改工作用户为root

- emby2Alist/nginx/conf.d/emby.js
- plex2Alist/nginx/conf.d/plex.js
https://github.com/bpking1/embyExternalUrl/issues/382
> fix(emby2Alist&plex2Alist): 精确远程链接的解码范围

- emby2Alist/README.md
- emby2Alist/nginx/conf.d/config/constant-ext.js
- emby2Alist/nginx/conf.d/exampleConfig/constant-all.js
- emby2Alist/nginx/conf.d/modules/emby-search.js
https://github.com/bpking1/embyExternalUrl/issues/397
> fix(emby2Alist): 修复搜索框指令对于历史配置的兼容问题

- alistWebAddExternalUrl/README.md
- alistWebAddExternalUrl/alistWebLaunchExternalPlayer.js
- emby2Alist/nginx/conf.d/modules/emby-v-media.js
- embyAddExternalUrl/nginx/conf.d/externalUrl.js
- embyWebAddExternalUrl/README.md
- embyWebAddExternalUrl/embyLaunchPotplayer.js
https://github.com/bpking1/embyExternalUrl/issues/394
https://greasyfork.org/zh-CN/scripts/514529-embylaunchpotplayer/discussions/265421#
> fix(emby&alistWebAddExternalUrl): 修复 PotPlayer 调用方式

- alistWebAddExternalUrl/README.md
- alistWebAddExternalUrl/alistWebLaunchExternalPlayer.js
- embyWebAddExternalUrl/README.md
- embyWebAddExternalUrl/embyLaunchPotplayer.js
https://greasyfork.org/zh-CN/scripts/514529-embylaunchpotplayer/discussions/266075
> fix(emby&alistWebAddExternalUrl): 修复剪切板 API 兼容性

- emby2Alist/nginx/conf.d/config/constant-ext.js
- emby2Alist/nginx/conf.d/emby.js
- emby2Alist/nginx/conf.d/exampleConfig/constant-all.js
- emby2Alist/nginx/conf.d/modules/emby-playback-info.js
fix(emby2Alist): 多版本播放源排序安全校验
feat(emby2Alist): 按规则分组进行多版本播放源排序
> feat(emby2Alist): 按规则分组进行多版本播放源排序

- emby2Alist/nginx/conf.d/modules/emby-playback-info.js
码率等数字执行 toLowerCase() 报错，增加一个判断
> fix(emby2Alist): 多版本播放源排序码率条件报错

- emby2Alist/CHANGELOG.md
- emby2Alist/nginx/conf.d/common/util.js
- emby2Alist/nginx/conf.d/config/constant-mount.js
- emby2Alist/nginx/conf.d/exampleConfig/constant-all.js
- plex2Alist/CHANGELOG.md
- plex2Alist/nginx/conf.d/common/util.js
- plex2Alist/nginx/conf.d/config/constant-mount.js
- plex2Alist/nginx/conf.d/exampleConfig/constant-all.js
https://github.com/chen3861229/embyExternalUrl/issues/76
> fix(emby2Alist&plex2Alist): 增强 addAlistSign特定情况覆盖

- emby2Alist/CHANGELOG.md
- emby2Alist/nginx/conf.d/common/events.js
- emby2Alist/nginx/conf.d/emby.js
- embyWebAddExternalUrl/README.md
- plex2Alist/CHANGELOG.md
- plex2Alist/nginx/conf.d/common/events.js
- plex2Alist/nginx/conf.d/plex.conf
- plex2Alist/nginx/conf.d/plex.js
https://github.com/chen3861229/embyExternalUrl/issues/78
> feat(plex2Alist): 解决上游服务双重响应头问题

- README.md
- emby2Alist/CHANGELOG.md
- emby2Alist/nginx/conf.d/config/constant-pro.js
- emby2Alist/nginx/conf.d/constant.js
- emby2Alist/nginx/conf.d/emby.js
- emby2Alist/nginx/conf.d/exampleConfig/constant-all.js
- emby2Alist/nginx/conf.d/modules/emby-live.js
- emby2Alist/nginx/conf.d/modules/emby-v-media.js
- plex2Alist/CHANGELOG.md
- plex2Alist/nginx/conf.d/config/constant-pro.js
- plex2Alist/nginx/conf.d/constant.js
- plex2Alist/nginx/conf.d/exampleConfig/constant-all.js
- plex2Alist/nginx/conf.d/exampleConfig/constant-main.js
- plex2Alist/nginx/conf.d/plex.js
https://github.com/bpking1/embyExternalUrl/issues/434
> feat(emby2Alist&plex2Alist): 新增 redirectConfig 参数

- emby2Alist/CHANGELOG.md
- emby2Alist/nginx/conf.d/common/util.js
- emby2Alist/nginx/conf.d/emby.js
- emby2Alist/nginx/conf.d/modules/emby-transcode.js
- emby2Alist/nginx/conf.d/modules/ngx-ext.js
- plex2Alist/CHANGELOG.md
- plex2Alist/nginx/conf.d/common/util.js
- plex2Alist/nginx/conf.d/modules/ngx-ext.js
- plex2Alist/nginx/conf.d/plex.js
https://github.com/bpking1/embyExternalUrl/issues/437
> fix(emby2Alist&plex2Alist): 统一 encodeURIComponent

- emby2Alist/CHANGELOG.md
- emby2Alist/nginx/conf.d/emby.js
https://github.com/bpking1/embyExternalUrl/issues/435
> fix(emby2Alist): 遵守上游的直接播放判断

- emby2Alist/CHANGELOG.md
- emby2Alist/nginx/conf.d/emby.js
- plex2Alist/CHANGELOG.md
- plex2Alist/nginx/conf.d/plex.js
https://github.com/bpking1/embyExternalUrl/issues/439
> fix(emby2Alist&plex2Alist): 区分远程链接的解码范围

- emby2Alist/nginx/conf.d/common/util.js
- plex2Alist/nginx/conf.d/common/util.js
https://github.com/chen3861229/embyExternalUrl/issues/82
> fix(emby2Alist&plex2Alist): 修复 getClientSelfAlistLink 编码

- emby2Alist/CHANGELOG.md
- emby2Alist/nginx/conf.d/emby.js
- emby2Alist/nginx/conf.d/modules/emby-v-media.js
https://github.com/bpking1/embyExternalUrl/issues/447
> fix(emby2Alist): 修复 directHlsConfig 错误替换的异步循环

- alistWebAddExternalUrl/README.md
- alistWebAddExternalUrl/alistWebLaunchExternalPlayer.js
- embyWebAddExternalUrl/README.md
- embyWebAddExternalUrl/embyLaunchPotplayer.js
https://github.com/bpking1/embyExternalUrl/issues/482
https://github.com/bpking1/embyExternalUrl/issues/478
https://greasyfork.org/zh-CN/scripts/514529-embylaunchpotplayer/discussions/273903
> feat(embyLaunchPotplayer): 提供 strm 播放链接直通开关

- emby2Alist/CHANGELOG.md
- emby2Alist/nginx/conf.d/custome/location/default.conf
- emby2Alist/nginx/conf.d/emby.conf
- plex2Alist/CHANGELOG.md
- plex2Alist/nginx/conf.d/custome/location/default.conf
- plex2Alist/nginx/conf.d/plex.conf
https://github.com/bpking1/embyExternalUrl/issues/492
> fix(emby2Alist&plex2Alist): 修复 include 错误
